# Generated by Django 2.1.7 on 2019-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
