# Generated by Django 2.1.7 on 2019-02-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='meaaage',
            new_name='message',
        ),
    ]
