# Generated by Django 2.1.7 on 2019-02-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190226_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decc',
            new_name='desc',
        ),
    ]
