# Generated by Django 2.1.7 on 2019-03-09 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='课程标签'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='教师告知'),
        ),
        migrations.AlterField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
