# Generated by Django 2.1.7 on 2019-03-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190226_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifyRecond',
            new_name='EmailVerifyRecord',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image/%Y/%m'),
        ),
    ]
