# Generated by Django 2.1.7 on 2019-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190309_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
